### ISSUE TITLE
Can't build with Titanium SDK 5.2.0.GA

### ISSUE THREAD

**Issue by spaksa** [yagitoshiro/TiSocketRocket#1]
When trying to build with this module I get the following error:

```
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld build/Intermediates/takki.build/Debug-iphonesimulator/takki.build/Objects-normal/x86_64/takki normal x86_64
[ERROR] (1 failure)
```

**Comment by yagitoshiro** [comment]
Hmm... did you built app for simulator? I just updated pre-built binary so try

`appc ti build -p ios --log-level trace`

and show me the log if problem still exists.

And what's your Titanium SDK / Xcode version?

**Comment by yagitoshiro** [comment]
@noodlesftw I just updated README.md and fixed wrong method name(createSocket -> createWebSocket).

**Comment by spaksa** [comment]
@yagitoshiro cool, building works now.

Getting a `CFNetwork SSLHandshake failed` error when trying to connect to a node.js server. Are you using socket.io?

**Comment by yagitoshiro** [comment]
No. Socket.IO implements its own protocol, while SocketRocket implements Websocket protocol(ws, wss). I added test server here:

https://github.com/yagitoshiro/TiSocketRocket/tree/master/server

You can run `npm install && npm start`` in this server directory.

**Comment by spaksa** [comment]
Ah cool. Working great! Where can I find SocketRocket's documentation?

**Comment by yagitoshiro** [comment]
see https://github.com/square/SocketRocket
